apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "nexus-repository.fullname" . }}-nexus-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: matthew@fortunka.co.uk
    privateKeySecretRef:
      name: {{ include "nexus-repository.fullname" . }}-nexus-letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.nexus.ingressClassName }}