apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nexus-repository.fullname" . }}-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: {{ include "nexus-repository.fullname" . }}-volume  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.storage.resourceGroupName }}
      shareName: {{ .Values.storage.shareName }}
    nodeStageSecretRef:
      name: {{ include "nexus-repository.fullname" . }}-secret-storage
      namespace: {{ include "nexus-repository.fullname" . }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl