apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-repository.fullname" . }}-secret-storage
  namespace: {{ include "nexus-repository.fullname" . }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storage.accountName | b64enc }}
  azurestorageaccountkey: {{ .Values.storage.primaryKey | b64enc }}