apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-repository.fullname" . }}-secret-init
  namespace: {{ include "nexus-repository.fullname" . }}
type: Opaque
data:
  admin_username: {{ .Values.nexus.admin.username | b64enc }}
  admin_password: {{ .Values.nexus.admin.password | b64enc }}